## Create a NumPy array:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## What is NumPy?
## NumPy is a Python library used for working with arrays.
## It also has functions for working in domain of linear algebra, fourier transform, and matrices.
## NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
## NumPy stands for Numerical Python.

## Why Use NumPy?

## In Python we have lists that serve the purpose of arrays, but they are slow to process.
## NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
## The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
## Arrays are very frequently used in data science, where speed and resources are very important.

## Less Memory

In [ ]:
import sys

python_list = list(range(100))
python_list[:4]

[0, 1, 2, 3]

In [ ]:
sys.getsizeof(python_list[0])

24

In [ ]:
sys.getsizeof(python_list[0])*len(python_list)

2400

In [ ]:
numpy_array = np.arange(100)
numpy_array[:4]

array([0, 1, 2, 3])

In [ ]:
numpy_array.nbytes

800

##  Speed

In [ ]:
import time

SIZE = 1000000

l1 = list(range(SIZE))
l2 = list(range(SIZE))

start_time = time.time()
l3 = [x+y for x, y in zip(l1, l2)]
end_time = time.time()
print("Python list took: ", end_time-start_time)

Python list took:  0.1394789218902588


In [ ]:
n1 = np.arange(SIZE)
n2 = np.arange(SIZE)
n1[:3], n2[:3]

(array([0, 1, 2]), array([0, 1, 2]))

In [ ]:
start_time = time.time()
n3 = n1 + n2
end_time = time.time()
print("Numpy array took: ", end_time-start_time)

Numpy array took:  0.006449222564697266


## 0-D Arrays
## 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
arr = np.array(42)

print(arr)

42


## 1-D Arrays
## An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## 2-D Arrays
## An array that has 1-D arrays as its elements is called a 2-D array.
## These are often used to represent matrix or 2nd order tensors.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D arrays
## An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions?

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Access Array Elements

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

## Slicing arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

## Negative Slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

## STEP

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

## COPY:

In [ ]:
# Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

## VIEW:

In [ ]:
# Make a view, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

In [ ]:
# Make a view, change the view, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)